biothings/utils/hub.py
docs/doc/docker_tutorial.rst
docs/index.rst

The following enhancements add support for SSH keys to the biothings.api hub.  Support for passwords is still maintained although blank passwords are no longer supported.
A tutorial document for using docker with biothings is also included.

Security Enhancement:  SSH authorized keys and passwords.

---

biothings/utils/dataload.py

Previous function does not handle list of dicts
Currently supported

handle cases of list of dicts

---

biothings/hub/datatransform/__init__.py
biothings/hub/datatransform/datatransform.py
biothings/hub/datatransform/datatransform_api.py
biothings/hub/datatransform/datatransform_mdb.py
biothings/hub/datatransform/histogram.py
docs/doc/datatransform.rst
docs/index.rst

This branch contains a tutorial on the datatransform module.  It also contains several documentation strings in the source code.  Some variables are renamed for clarity.
The tutorial has been given a cursory review by Chunlei and a review by Sebastian.

datatransform.rst - datatransform documentation

---

biothings/hub/webapp/src/Build.vue
biothings/hub/webapp/src/BuildGrid.vue
biothings/hub/webapp/src/DataSource.vue
biothings/hub/webapp/src/JobSummary.vue

Date and limit filters will lower loading times on Build page on studio web app.

Add build date filters

---

.codacy.yml
.prospector.yml

Add configuration files so Codacy checks will be more meaningful:
- Disable all checks for tests (in directory tests and biothings/tests)
- Disable D212 for PEP257, so that only D213 is in effect -- docstring summary start on the second line

Update Codacy related config

---

biothings/utils/manager.py

This should fix Issue #101.
Also, it adds a lot more comments and notes regarding how the JobManager and related parts work.

Fix hub brokenprocesspool

---

biothings/hub/dataexport/ids.py
biothings/utils/aws.py
biothings/utils/hub.py
tests/utils/disabled_test_s3_utils.py

Update boto to boto3

---

biothings/utils/es.py

I tested @zcqian's [solution](https://github.com/biothings/biothings.api/issues/165#issuecomment-875807591) on mygeneset hub creating a new build, and uploading a full release snapshot to AWS. The process completed successfully.

Fix "Doctype error message on ES7" (#165)

---

biothings/tests/web.py

Fixes issue #212 
- Added a conditional statement to check for Elasticsearch 8 and update the bulk endpoint to remove the document type.
- The request now prints the text of any general exception on exit. (for debugging purposes)
- Some minor code cleaning.

Update bulk endpoint for es8: ingesting data in local webapp tests.

---

biothings/hub/dataload/dumper.py

Remove quotation marks around etag-based version strings.

Remove etag quotes

---

biothings/web/query/engine.py
tests/web/query/engine.py

Allow changing the es index (#280)

---

biothings/hub/databuild/builder.py
biothings/utils/mongo.py

This PR fixes issue https://github.com/biothings/biothings.api/issues/282. It introduces the following changes:
1. In `doc_feeder` function, a MongoDB session is created explicitly for the `collection.find` cursor, and the session is scheduled to refresh every 5 minutes (configurable with the new `session_refresh_interval` parameter) to keep the cursor alive.
2. Logging in `doc_feeder` is restored and now set to `DEBUG` level.
3. Logger instance to `doc_feeder` is explicitly passed from its callers.
4. Code cleaning in `mongo.py` module.

Fix to Issue#282

---

biothings/utils/mongo.py

This PR revises logging statements in `doc_feeder` function, as described in https://github.com/biothings/biothings.api/issues/282#issuecomment-1543195002

revise logging statements

---

biothings/utils/dotfield.py

Using `orjson` can reduce the running time of `make_object()` function by 50%, and `orjson` is already a dependency.

Orjson implementation of `dotfield` module

---

.gitignore
biothings/tests/web.py
setup.py

Upgrade tornado to 6.4.0

---

biothings/hub/dataindex/indexer.py
biothings/hub/dataindex/indexer_schedule.py
biothings/hub/dataindex/snapshooter.py
biothings/hub/dataindex/snapshot_task.py
tests/hub/dataindex/test_scheduler.py

When we have a misalignment with the amount of documents uploaded to MongoDB (or whatever database in this case, but it appears that the indexer environment targets MongoDB), there was a fairly confusing error message that this PR attempts to improve upon

Improve index error messaging

---

biothings/utils/postgresql.py
tests/utils/test_postgresql.py

Added `Database` and `Collection` classes to setup and connect to a PostgreSQL database. The `Database` class manages connections and grants access to collections, while the `Collection` class represents individual tables and supports CRUD operations (find, insert_one, update_many, replace_one, remove) and utility methods (rename, count, drop, exists, list_tables).

PostgreSQL Collection

---

biothings/cli/web_app.py

New output using the `fda_drugs` plugin as a test
```
(biothings) jschaff@tsri-ubuntu:~/workspace/biothings/pending.api/plugins/fda_drugs$ biothings-cli dataplugin serve
[12:16:43] INFO     Registering 'fda_drugs' to dump/upload managers                                                                                                                                                                                                                                                           
Serving data plugin source: fda_drugs
Found collection: fda_drugs; counting...Done (49108 documents)
Listening on http://localhost:9999
View all available routes: http://localhost:9999/
╭─ http://localhost:9999/fda_drugs ────────────────────────────────────────────────────────────────────────────────────────── …
```

Correct our command-line web-app find API call

---

biothings/hub/__init__.py
biothings/web/launcher.py

Issue: https://github.com/biothings/biothings.api/issues/363#event-16848513526

Suppress logs for elastic transport

---

biothings/web/handlers/query.py

Issue: https://github.com/biothings/biothings.api/issues/393

Fix mutation in metadata endpoint.

---

biothings/web/handlers/query.py

Issue https://github.com/biothings/biothings.api/issues/393

Refactor filtering of underscore-prefixed keys from meta dictionary
