- biothings/hub/datatransform/datatransform.py
- biothings/hub/datatransform/datatransform_mdb.py
- biothings/tests/test_datatransform.py
If documents had identical keys, strange things were happening.  In effect, the number of output documents was the number of input documents (with identical keys) squared.  The fix in this patch asserts that duplicate keys are not stored internally.  Further, logging improvements were made.
All tests in test_datatransform.py now pass.
> DataTransform duplicate key bug

- biothings/hub/webapp/src/App.vue
Expands the hitbox of the toolbar's links to the entirety of the button and not just the text, also if the link is an exact match it gives it an "active" class, which shows it greyed out to give better navigation.
> Update header links

- biothings/hub/webapp/src/Build.vue
- biothings/hub/webapp/src/DataSource.vue
- makes tabs for each build on the Builds page independent
- removes tooltips from buttons on the Sources page (which were negatively interfering with other more critical tooltips)
- buttons on the Sources page will be highlighted yellow if their action is being performed (e.g., if a source is currently uploading, the upload button will turn yellow)
> Fix tooltip 83

- biothings/hub/webapp/src/MappingMap.vue
- docs/doc/hub_tutorial.rst
- docs/doc/standalone.rst
- docs/doc/studio.rst
- docs/doc/studio_guide.rst
- docs/doc/studio_tutorial.rst
- docs/doc/utils.rst
This PR fixes some typos and improved some wordings in the documentation. Most of them are in:
- `docs/doc/studio_tutorial.rst`
- `docs/doc/studio_guide.rst`
There is a minor grammar issue in the text of this JS file:
- `hub/webapp/src/MappingMap.vue`
in which `This will be replace ...` should be `This will replace ...`.
The same issue exists in the following two files too:
- `hub/webapp/dist/assets/js/app.7dd5cf82.js.map`
- `hub/webapp/dist/assets/js/app.7dd5cf82.js`
But since these two files seem to be generated automatically by some JS compilation process,  I didn't modify them.
The invisible trailing spaces on a few lines were removed automatically by my editor (Emacs).
> Documentation improvements

- setup.py
Freezes aiohttp to version 3.6.2, because version 3.7 is not compatible.
> Update hub and web requirements

- biothings/hub/webapp/src/App.vue
- biothings/hub/webapp/src/JobSummary.vue
- biothings/hub/webapp/src/LogViewer.vue
Moves indicators from top menu bar to bottom. Makes the log window larger when expanded. Fixes #91
> Bottombar changes

- docs/doc/hub_tutorial.rst
Replace:
biothings.dataload -> biothings.hub.dataload
biothings.databuild -> biothings.hub.databuild
biothings/dataload -> biothings/hub/dataload
biothings/databuild -> biothings/hub/databuild
There is still more outdated information, but these changes fix many of the examples.
> Update Hub Docs: Fix broken urls, paths, and imports

- biothings/hub/webapp/src/DataSourceGrid.vue
Since 'bases' is not guaranteed to be present best to add another condition in case any condition pair short circuits.  "includes" is an array prototype method and can't be called if undefined.  Program assumes it exists, this will add a check prior to call.
> add check to array field causing issues before call

- biothings/hub/dataload/dumper.py
- use blocksize option from ftplib, change formatting of line
- implement function for optimal block_size lookup
- added list of known optimal sizes
Resolves Issue #117
> Add option for FTP buffer size:

- biothings/utils/web/analytics.py
- Implement new generation to produce deterministic, anonymous IDs based on user IP address and User Agent string.
- Add optional option to control the behavior of which generation method to use. To use the new behavior, explicitly set `GA_UID_GENERATOR_VERSION = 2` in config
> Add new GA Client/User ID generator

- biothings/hub/databuild/builder.py
Check dump/upload jobs status values, if not "success", it will unset the document, so that `whatsnewcomparedto` does not return the source as new. Fixes Issue #123
> Ensure source dump/upload successful before notifying via whatsnew

- biothings/utils/version.py
Previously it blindly uses the url from "origin". This alias may not exist, or the active branch might not be tracking origin.
Resolves Issue #120
> get_version: get URL from actual tracked remote branch

- biothings/utils/hub.py
The original code intends to hide the functionality, but in practice it does not work (explained later)
This change makes sure that hub can run when pyinotify is not installed or available (e.g. on macOS, various BSDs)
The code has been somewhat tested:
1. It does function like before on Linux with inotify feature and the pyinotify package installed (reloads on change detected)
2. It does function on other OS w/o inotify, this case the Tornado based reloader is used. Tested on macOS and works, should also work on BSD and others.
3. It does function on Linux w/o inotify (docker emulated x86_64 on M1 Macs), remove the pyinotify package and it should work
What's not tested:
1. Trying to create an inotify based reloader should raise an exception when pyinotify package is not installed. Didn't …
> Properly prevent depending on pyinotify

- biothings/hub/dataload/dumper.py
Manually tested and seems to work fine. Instead of just using 'main' as the default branch, `GitDumper` will actually try to see what the default branch is on the remote repo.
I did not test the case where `DEFAULT_BRANCH` is explicitly set (does anything use this?)
Also, according to my understanding of the git-scm docs, remote could have no default branch (no HEAD). However I cannot find a way to create that kind of test environment, and most likely the fallback solutions will work fine (return `None` and guess based on heuristics), and if it actually affects anyone it shouldn't be hard to fix.
Let me know the part about `DEFAULT_BRANCH` because I changed the default to `None` so we would know that it's explicitly set to some value, I don't think this will break anything because I don't …
> Fix gitdumper default branch

- biothings/utils/configuration.py
Fixes runtime "cannot deepcopy this pattern object" error.
> Fix typo in argument name

- biothings/utils/configuration.py
Reverts biothings/biothings.api#161
> Revert "Fix typo in argument name"

- biothings/hub/dataload/dumper.py
Properly handle date and time information according to RFC 7231. Uses the built-in `email` library to parse HTTP-date (which is a subset of date defined for Internet Message Format (email).
Compared to the previous implementation:
- it correctly uses UTC timezone for remote dates
- properly parses the date and time in `Last-Modified` field, and adds support for obsolete date time formats.
> Fix Issue #85

- biothings/hub/dataload/dumper.py
Introduced a instance variable `to_delete` and a method `post_dump_delete_files` to `BaseDumper`.
`to_delete` includes a list of relative path of files and directories that need to be deleted. Descendants of this class can populate the list by appending to it.
`post_dump_delete_files` should be invoked in `post_dump` method to delete the files synchronously, while `post_dump` is run in a separate thread by the `dump` method. Descendants of `BaseDumper` should call this method explicitly.
`post_dump_delete_files` does not delete files recursively and only supports deleting regular files and directories. And, it specifically avoids using `shutil.rmtree` so that deletions can be logged and minimizes the risk of accidentally deleting files. It is also hardened against directory traversal …
> Add delete file functionality to BaseDumper

- biothings/hub/autoupdate/uploader.py
- Uses `AWS4Auth` to sign requests when creating repository, configurable per installation target
- Removes old S3 credential mechanisms when creating repository (the old way is unsafe and no longer supported since Elasticsearch 6.0)
- Allows extra repository settings to be set, per installation target
> Add AWS4 Authentication when restoring snapshots

- biothings/hub/dataplugin/assistant.py
- biothings/hub/dataplugin/uploader.py.tpl
- biothings/utils/parsers.py
To use them in manifest based plugins, create the manifest.json file to contain something like this:
```json
{
"uploader" : {
"parser" : "biothings.util.parsers:ndjson_parser",
"parser_kwargs": {
"patterns": ["data.ndjson", "data_extra_*.ndjson"]
}
}
}
> Add Bundled, Configurable Parsers

- biothings/hub/dataload/dumper.py
Removes the prepended "W/" from datasource version strings when they use weak ETags.
> Remove weak etag prefix in version strings

- biothings/hub/datarelease/publisher.py
- biothings/hub/datarelease/releasenote.py
- tests/hub/datarelease/conftest.py
- tests/hub/datarelease/dummy_config.py
- tests/hub/datarelease/pytest.ini
- tests/hub/datarelease/test_releasenote.py
The whole fix involves two parts:
- **Biothings.api Implementation:** When generating a release note between two builds, $x$ and $y$, the Publisher in Biothings.api codebase will read 3 major pieces of information for each build, i.e. _**build stats**_, _**datasource stats**_, and _**mappings**_. However, if a build $x$ has a `cold_collection`, which corresponds to another build $x'$, the Publisher should read the combined stats/mappings of $x$ and $x'$.
1. For _**build stats**_, the Publisher will read the combined stats in $x$, no need to read $x'$.
1. For _**datasource stats**_, the Publisher will read the datasource fields in both $x$ and $x'$
1. For _**mappings**_, the Publisher will read the mapping fields in both $x$ and $x'$
Note that **Biothings.api Implementatio** should work …
> Fix to MyVariant Issue#103

- biothings/utils/mongo.py
This PR turns off some debugging logs, introduced as a result of https://github.com/biothings/biothings.api/issues/282, from `doc_feeder` function.
> turn off some debugging logs in `doc_feeder`

- biothings/hub/datatransform/datatransform_mdb.py
`from networkx import nx` doesn't work in networkx versions >=2.6, only `import networkx as nx` works.
Relevant setup lines: https://github.com/biothings/biothings.api/blob/2c23e0da57b7c64b0a19e534b9f75da70f140159/setup.py#L91C1-L92
The setup installs networkx v2.8.8 for python >=3.7 which causes an ImportError when we try to import it.
> Fix networkx import

- biothings/web/query/builder.py
- biothings/web/services/namespace.py
This add the `ESResultFormatter` to the query builder so that when we extract the metadata fields for the endpoint, we include all fields and properties of the fields as well when we create the full set
> metadata query logical enhancements and bugfixes

- biothings/utils/sqlite3.py
Here's some performance metrics on a relatively small plugin of ~50k documents
```
<new branch>
(biothings) jschaff@tsri-ubuntu:~/workspace/biothings/pending.api/plugins/fda_drugs$ biothings-cli dataplugin upload
[15:58:38] INFO     Registering 'fda_drugs' to dump/upload managers 
INFO     Uploading to the DB...
[15:58:39] INFO     insert time: 0.22862836300009803
INFO     insert time: 0.06624280699907104
INFO     insert time: 0.06812734000050114
INFO     insert time: 0.07389820600110397
INFO     insert time: 0.058063160000529024
INFO     Done[0.92s] with 48022 docs
INFO     Renaming collection 'fda_drugs' to 'fda_drugs_archive_20240506_ukQtnR1S' for archiving purpose.
INFO     Renaming collection 'fda_drugs_temp_KACOAEWD' to 'fda_drugs'
INFO     Cleaning old archive/temp collection …
```
> Add more idiomatic sqlite multiple document insert

- biothings/cli/utils.py
Before we do anything we execute a call to `load_plugin`
```python
_plugin = load_plugin(plugin_name, dumper=True, uploader=False, logger=logger)
def load_plugin(plugin_name: str = None, dumper: bool = True, uploader: bool = True, logger: logging.Logger = None):
"""
Return a plugin object for the given plugin_name.
If dumper is True, include a dumper instance in the plugin object.
If uploader is True, include uploader_classes in the plugin object.
If <plugin_name> is not valid, raise the proper error and exit.
"""
logger = logger or get_logger(__name__)
_plugin_name, working_dir = get_plugin_name(plugin_name, with_working_dir=True)
if plugin_name is None:
data_plugin_dir = pathlib.Path(working_dir)
data_folder = pathlib.Path(".").resolve().absolute()
plugin_args = {"plugin_path": …
```
> Add advanced plugin support for the command line tooling 

- biothings/hub/dataplugin/assistant.py
The imp module has been deprecated since Python 3.4, which was released in March 2014. Python 3.12, released in October 2023, removed support for the imp module entirely.
> Replace deprecated imp module with importlib

- biothings/hub/databuild/builder.py
In the event an error occurs in one build config, every item in the list afterwards will contain the error. Resetting the error to None inside the loop fixes this.
> Build Config Err Fix

- biothings/web/query/pipeline.py
- tests/web/connections.py
- tests/web/test_es_exceptions.py
The application should raise an exception when there is a timeout connection when connecting to the Elasticsearch.
However, there is an error in the exception handling function:
```
AttributeError: 'ConnectionTimeout' object has no attribute 'error'
```
There bug is in this line:
https://github.com/biothings/biothings.api/blob/8a430d25c8f31e7d43c74317887cee5feab32fd6/biothings/web/query/pipeline.py#L134
Refactor the exception handling function.
> Refactor ES exceptions

- biothings/utils/dataload.py
- tests/hub/dataload/unlist.py
- tests/hub/dataload/unlist_incexcl.py
This PR improves the `unlist` and `unlist_incexcl` functions to correctly handle deeply nested lists and dictionaries. It ensures that single-element lists are properly unlisted, even within nested structures.
Fixes issue #7
> Fix Unlisting Logic in Dataload Utils

- biothings/web/query/formatter.py
A KeyError was being raised in the transformation logic whenever a list item did not contain the target_field. In particular, this occurred when making a query to mychem.info with jmespath_exclude_empty=true, causing the transformation step to attempt dictionary access on a missing key.
```
curl --location --globoff 'https://mychem.info/v1/query?size=1000&fields=drugcentral.bioactivity%2Cdrugcentral.xrefs.umlscui%2Cdrugcentral.synonyms&jmespath_exclude_empty=true&always_list=drugcentral.bioactivity&jmespath=drugcentral.bioactivity%7C[%3F!action_type%20%20%26%26%20length(uniprot[%3Funiprot_id%3D%3D%27P29274%27])%20%3E%20%600%60]' \
--header 'Content-Type: application/json' \
--data '{
"q": ["P29274"],
"scopes": "drugcentral.bioactivity.uniprot.uniprot_id"
}'
```
This query would raise a …
> jmespath exclude_empty fix

- biothings/cli/operations.py
This should prevent the .biothings_hub folder from being created until an actual operation has been run
> Move hub commits to inner scope

- biothings/cli/dataplugin.py
- biothings/cli/operations.py
- biothings/hub/dataload/dumper.py
- biothings/utils/sqlite3.py
- Remove the `List` type for `list` data structure calls
- Add exception handling for the command-line dumper `set_release` function call
- Fix the manifest validation plugin path determination
- Improve the warning message for `LastModifiedHTTPDumper` remote determination function
> Various bugfixes and cleanup

- biothings/hub/dataindex/indexer_task.py
The `doc_type` was deprecated in Elasticsearch 7.x.
It was removed entirely in Elasticsearch 8.x and the corresponding Python client.
> Remove Deprecated doc_type

- biothings/cli/assistant.py
- biothings/cli/dataplugin.py
- biothings/cli/exceptions.py
- biothings/cli/manager.py
- biothings/cli/operations.py
Revert back to leveraging the simplified `CLIJobManager` for most cases. Until we can refactor our configuration environment to work with parallel jobs, we'll leverage this manager for compatibility.
> Isolate cli job management

- biothings/web/connections.py
- biothings/web/query/builder.py
- biothings/web/query/engine.py
- docs/tutorial/web.rst
- pyproject.toml
Resolve #398
- Removed `elasticsearch_dsl` as a separate dependency
- Replaced all imports from `elasticsearch_dsl` with `elasticsearch.dsl`
- Updated version detection logic as DSL version now aligns with the base `elasticsearch` package
Note:This change introduces a breaking change for environments using `Python < 3.8`, where `elasticsearch_dsl` is still required as a separate dependency. However, this is not considered an issue for the upcoming `biothings 1.1.x` release, as support for `Python <= 3.8` will be officially dropped.
> Remove deprecated elasticsearch_dsl
